# Generated by Django 5.2.8 on 2026-07-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_branch_commit_issue_pullrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='commited_at',
            new_name='committed_at',
        ),
    ]
